//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAESJobs.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHistory
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Employer { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public int Current { get; set; }
        public string Title { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
