//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAESJobs.Client.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityUserOfstringIdentityUserLoginIdentityUserRoleIdentityUserClaim39AeZpW1", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.AspNet.Identity.EntityFramework" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAESJobs.Client.UserService.IdentityUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAESJobs.AccountLibrary.ApplicationUser))]
    public partial class IdentityUserOfstringIdentityUserLoginIdentityUserRoleIdentityUserClaim39AeZpW1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityUser", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.AspNet.Identity.EntityFramework" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAESJobs.AccountLibrary.ApplicationUser))]
    public partial class IdentityUser : WcfAESJobs.Client.UserService.IdentityUserOfstringIdentityUserLoginIdentityUserRoleIdentityUserClaim39AeZpW1 {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleForm", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RoleForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ischeckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAESJobs.Client.UserService.URole roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ischecked {
            get {
                return this.ischeckedField;
            }
            set {
                if ((this.ischeckedField.Equals(value) != true)) {
                    this.ischeckedField = value;
                    this.RaisePropertyChanged("ischecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAESJobs.Client.UserService.URole role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URole", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class URole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationForm", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class LocationForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ischeckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAESJobs.Client.UserService.ULocation locationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ischecked {
            get {
                return this.ischeckedField;
            }
            set {
                if ((this.ischeckedField.Equals(value) != true)) {
                    this.ischeckedField = value;
                    this.RaisePropertyChanged("ischecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAESJobs.Client.UserService.ULocation location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ULocation", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ULocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreLocations", Namespace="http://schemas.datacontract.org/2004/07/WCFAESJobs.WebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class StoreLocations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Location_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Location_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Location_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location_City {
            get {
                return this.Location_CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Location_CityField, value) != true)) {
                    this.Location_CityField = value;
                    this.RaisePropertyChanged("Location_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location_ID {
            get {
                return this.Location_IDField;
            }
            set {
                if ((this.Location_IDField.Equals(value) != true)) {
                    this.Location_IDField = value;
                    this.RaisePropertyChanged("Location_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location_Name {
            get {
                return this.Location_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Location_NameField, value) != true)) {
                    this.Location_NameField = value;
                    this.RaisePropertyChanged("Location_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkHistory_User", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WorkHistory_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Current {
            get {
                return this.CurrentField;
            }
            set {
                if ((this.CurrentField.Equals(value) != true)) {
                    this.CurrentField = value;
                    this.RaisePropertyChanged("Current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Employer {
            get {
                return this.EmployerField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerField, value) != true)) {
                    this.EmployerField = value;
                    this.RaisePropertyChanged("Employer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EducationHistory_User", Namespace="http://schemas.datacontract.org/2004/07/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EducationHistory_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((this.DegreeField.Equals(value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationLevel {
            get {
                return this.EducationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLevelField, value) != true)) {
                    this.EducationLevelField = value;
                    this.RaisePropertyChanged("EducationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Institution {
            get {
                return this.InstitutionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionField, value) != true)) {
                    this.InstitutionField = value;
                    this.RaisePropertyChanged("Institution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Major {
            get {
                return this.MajorField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorField, value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindById", ReplyAction="http://tempuri.org/ILoginService/FindByIdResponse")]
        WcfAESJobs.AccountLibrary.ApplicationUser FindById(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindById", ReplyAction="http://tempuri.org/ILoginService/FindByIdResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByIdAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindByName", ReplyAction="http://tempuri.org/ILoginService/FindByNameResponse")]
        WcfAESJobs.AccountLibrary.ApplicationUser FindByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindByName", ReplyAction="http://tempuri.org/ILoginService/FindByNameResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Create", ReplyAction="http://tempuri.org/ILoginService/CreateResponse")]
        void Create(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Create", ReplyAction="http://tempuri.org/ILoginService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindByEmail", ReplyAction="http://tempuri.org/ILoginService/FindByEmailResponse")]
        WcfAESJobs.AccountLibrary.ApplicationUser FindByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/FindByEmail", ReplyAction="http://tempuri.org/ILoginService/FindByEmailResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetRolesAsync", ReplyAction="http://tempuri.org/ILoginService/GetRolesAsyncResponse")]
        string[] GetRolesAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetRolesAsync", ReplyAction="http://tempuri.org/ILoginService/GetRolesAsyncResponse")]
        System.Threading.Tasks.Task<string[]> GetRolesAsyncAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Update", ReplyAction="http://tempuri.org/ILoginService/UpdateResponse")]
        void Update(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Update", ReplyAction="http://tempuri.org/ILoginService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/IsInRole", ReplyAction="http://tempuri.org/ILoginService/IsInRoleResponse")]
        bool IsInRole(WcfAESJobs.AccountLibrary.ApplicationUser user, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/IsInRole", ReplyAction="http://tempuri.org/ILoginService/IsInRoleResponse")]
        System.Threading.Tasks.Task<bool> IsInRoleAsync(WcfAESJobs.AccountLibrary.ApplicationUser user, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetRoleForm", ReplyAction="http://tempuri.org/ILoginService/GetRoleFormResponse")]
        WcfAESJobs.Client.UserService.RoleForm[] GetRoleForm(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetRoleForm", ReplyAction="http://tempuri.org/ILoginService/GetRoleFormResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.RoleForm[]> GetRoleFormAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddUserToRoleByForm", ReplyAction="http://tempuri.org/ILoginService/AddUserToRoleByFormResponse")]
        void AddUserToRoleByForm(string UserID, WcfAESJobs.Client.UserService.RoleForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddUserToRoleByForm", ReplyAction="http://tempuri.org/ILoginService/AddUserToRoleByFormResponse")]
        System.Threading.Tasks.Task AddUserToRoleByFormAsync(string UserID, WcfAESJobs.Client.UserService.RoleForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetLocationForm", ReplyAction="http://tempuri.org/ILoginService/GetLocationFormResponse")]
        WcfAESJobs.Client.UserService.LocationForm[] GetLocationForm(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetLocationForm", ReplyAction="http://tempuri.org/ILoginService/GetLocationFormResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.LocationForm[]> GetLocationFormAsync(WcfAESJobs.AccountLibrary.ApplicationUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddUserToLocationByForm", ReplyAction="http://tempuri.org/ILoginService/AddUserToLocationByFormResponse")]
        void AddUserToLocationByForm(string UserID, WcfAESJobs.Client.UserService.LocationForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddUserToLocationByForm", ReplyAction="http://tempuri.org/ILoginService/AddUserToLocationByFormResponse")]
        System.Threading.Tasks.Task AddUserToLocationByFormAsync(string UserID, WcfAESJobs.Client.UserService.LocationForm[] form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetLocationsByUserID", ReplyAction="http://tempuri.org/ILoginService/GetLocationsByUserIDResponse")]
        WcfAESJobs.Client.UserService.StoreLocations[] GetLocationsByUserID(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetLocationsByUserID", ReplyAction="http://tempuri.org/ILoginService/GetLocationsByUserIDResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.StoreLocations[]> GetLocationsByUserIDAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetWorkHistoryByUser", ReplyAction="http://tempuri.org/ILoginService/GetWorkHistoryByUserResponse")]
        WcfAESJobs.Client.UserService.WorkHistory_User[] GetWorkHistoryByUser(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetWorkHistoryByUser", ReplyAction="http://tempuri.org/ILoginService/GetWorkHistoryByUserResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.WorkHistory_User[]> GetWorkHistoryByUserAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetEducationHistoryByUser", ReplyAction="http://tempuri.org/ILoginService/GetEducationHistoryByUserResponse")]
        WcfAESJobs.Client.UserService.EducationHistory_User[] GetEducationHistoryByUser(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetEducationHistoryByUser", ReplyAction="http://tempuri.org/ILoginService/GetEducationHistoryByUserResponse")]
        System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.EducationHistory_User[]> GetEducationHistoryByUserAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddEducationHistory", ReplyAction="http://tempuri.org/ILoginService/AddEducationHistoryResponse")]
        void AddEducationHistory(string UserID, WcfAESJobs.Client.UserService.EducationHistory_User[] education);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddEducationHistory", ReplyAction="http://tempuri.org/ILoginService/AddEducationHistoryResponse")]
        System.Threading.Tasks.Task AddEducationHistoryAsync(string UserID, WcfAESJobs.Client.UserService.EducationHistory_User[] education);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddWorkHistory", ReplyAction="http://tempuri.org/ILoginService/AddWorkHistoryResponse")]
        void AddWorkHistory(string UserID, WcfAESJobs.Client.UserService.WorkHistory_User[] work);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/AddWorkHistory", ReplyAction="http://tempuri.org/ILoginService/AddWorkHistoryResponse")]
        System.Threading.Tasks.Task AddWorkHistoryAsync(string UserID, WcfAESJobs.Client.UserService.WorkHistory_User[] work);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/DeleteWorkHistoryByID", ReplyAction="http://tempuri.org/ILoginService/DeleteWorkHistoryByIDResponse")]
        void DeleteWorkHistoryByID(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/DeleteWorkHistoryByID", ReplyAction="http://tempuri.org/ILoginService/DeleteWorkHistoryByIDResponse")]
        System.Threading.Tasks.Task DeleteWorkHistoryByIDAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/DeleteEducationHistoryByID", ReplyAction="http://tempuri.org/ILoginService/DeleteEducationHistoryByIDResponse")]
        void DeleteEducationHistoryByID(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/DeleteEducationHistoryByID", ReplyAction="http://tempuri.org/ILoginService/DeleteEducationHistoryByIDResponse")]
        System.Threading.Tasks.Task DeleteEducationHistoryByIDAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UpdateEducationHistory", ReplyAction="http://tempuri.org/ILoginService/UpdateEducationHistoryResponse")]
        void UpdateEducationHistory(WcfAESJobs.Client.UserService.EducationHistory_User[] EduHist, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UpdateEducationHistory", ReplyAction="http://tempuri.org/ILoginService/UpdateEducationHistoryResponse")]
        System.Threading.Tasks.Task UpdateEducationHistoryAsync(WcfAESJobs.Client.UserService.EducationHistory_User[] EduHist, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UpdateWorkHistory", ReplyAction="http://tempuri.org/ILoginService/UpdateWorkHistoryResponse")]
        void UpdateWorkHistory(WcfAESJobs.Client.UserService.WorkHistory_User[] WorkHist, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UpdateWorkHistory", ReplyAction="http://tempuri.org/ILoginService/UpdateWorkHistoryResponse")]
        System.Threading.Tasks.Task UpdateWorkHistoryAsync(WcfAESJobs.Client.UserService.WorkHistory_User[] WorkHist, string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : WcfAESJobs.Client.UserService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<WcfAESJobs.Client.UserService.ILoginService>, WcfAESJobs.Client.UserService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfAESJobs.AccountLibrary.ApplicationUser FindById(string userId) {
            return base.Channel.FindById(userId);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByIdAsync(string userId) {
            return base.Channel.FindByIdAsync(userId);
        }
        
        public WcfAESJobs.AccountLibrary.ApplicationUser FindByName(string userName) {
            return base.Channel.FindByName(userName);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByNameAsync(string userName) {
            return base.Channel.FindByNameAsync(userName);
        }
        
        public void Create(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task CreateAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.CreateAsync(user);
        }
        
        public WcfAESJobs.AccountLibrary.ApplicationUser FindByEmail(string email) {
            return base.Channel.FindByEmail(email);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.AccountLibrary.ApplicationUser> FindByEmailAsync(string email) {
            return base.Channel.FindByEmailAsync(email);
        }
        
        public string[] GetRolesAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetRolesAsync(user);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRolesAsyncAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetRolesAsyncAsync(user);
        }
        
        public void Update(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.UpdateAsync(user);
        }
        
        public bool IsInRole(WcfAESJobs.AccountLibrary.ApplicationUser user, string role) {
            return base.Channel.IsInRole(user, role);
        }
        
        public System.Threading.Tasks.Task<bool> IsInRoleAsync(WcfAESJobs.AccountLibrary.ApplicationUser user, string role) {
            return base.Channel.IsInRoleAsync(user, role);
        }
        
        public WcfAESJobs.Client.UserService.RoleForm[] GetRoleForm(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetRoleForm(user);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.RoleForm[]> GetRoleFormAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetRoleFormAsync(user);
        }
        
        public void AddUserToRoleByForm(string UserID, WcfAESJobs.Client.UserService.RoleForm[] form) {
            base.Channel.AddUserToRoleByForm(UserID, form);
        }
        
        public System.Threading.Tasks.Task AddUserToRoleByFormAsync(string UserID, WcfAESJobs.Client.UserService.RoleForm[] form) {
            return base.Channel.AddUserToRoleByFormAsync(UserID, form);
        }
        
        public WcfAESJobs.Client.UserService.LocationForm[] GetLocationForm(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetLocationForm(user);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.LocationForm[]> GetLocationFormAsync(WcfAESJobs.AccountLibrary.ApplicationUser user) {
            return base.Channel.GetLocationFormAsync(user);
        }
        
        public void AddUserToLocationByForm(string UserID, WcfAESJobs.Client.UserService.LocationForm[] form) {
            base.Channel.AddUserToLocationByForm(UserID, form);
        }
        
        public System.Threading.Tasks.Task AddUserToLocationByFormAsync(string UserID, WcfAESJobs.Client.UserService.LocationForm[] form) {
            return base.Channel.AddUserToLocationByFormAsync(UserID, form);
        }
        
        public WcfAESJobs.Client.UserService.StoreLocations[] GetLocationsByUserID(string UserID) {
            return base.Channel.GetLocationsByUserID(UserID);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.StoreLocations[]> GetLocationsByUserIDAsync(string UserID) {
            return base.Channel.GetLocationsByUserIDAsync(UserID);
        }
        
        public WcfAESJobs.Client.UserService.WorkHistory_User[] GetWorkHistoryByUser(string UserID) {
            return base.Channel.GetWorkHistoryByUser(UserID);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.WorkHistory_User[]> GetWorkHistoryByUserAsync(string UserID) {
            return base.Channel.GetWorkHistoryByUserAsync(UserID);
        }
        
        public WcfAESJobs.Client.UserService.EducationHistory_User[] GetEducationHistoryByUser(string UserID) {
            return base.Channel.GetEducationHistoryByUser(UserID);
        }
        
        public System.Threading.Tasks.Task<WcfAESJobs.Client.UserService.EducationHistory_User[]> GetEducationHistoryByUserAsync(string UserID) {
            return base.Channel.GetEducationHistoryByUserAsync(UserID);
        }
        
        public void AddEducationHistory(string UserID, WcfAESJobs.Client.UserService.EducationHistory_User[] education) {
            base.Channel.AddEducationHistory(UserID, education);
        }
        
        public System.Threading.Tasks.Task AddEducationHistoryAsync(string UserID, WcfAESJobs.Client.UserService.EducationHistory_User[] education) {
            return base.Channel.AddEducationHistoryAsync(UserID, education);
        }
        
        public void AddWorkHistory(string UserID, WcfAESJobs.Client.UserService.WorkHistory_User[] work) {
            base.Channel.AddWorkHistory(UserID, work);
        }
        
        public System.Threading.Tasks.Task AddWorkHistoryAsync(string UserID, WcfAESJobs.Client.UserService.WorkHistory_User[] work) {
            return base.Channel.AddWorkHistoryAsync(UserID, work);
        }
        
        public void DeleteWorkHistoryByID(int Id) {
            base.Channel.DeleteWorkHistoryByID(Id);
        }
        
        public System.Threading.Tasks.Task DeleteWorkHistoryByIDAsync(int Id) {
            return base.Channel.DeleteWorkHistoryByIDAsync(Id);
        }
        
        public void DeleteEducationHistoryByID(int Id) {
            base.Channel.DeleteEducationHistoryByID(Id);
        }
        
        public System.Threading.Tasks.Task DeleteEducationHistoryByIDAsync(int Id) {
            return base.Channel.DeleteEducationHistoryByIDAsync(Id);
        }
        
        public void UpdateEducationHistory(WcfAESJobs.Client.UserService.EducationHistory_User[] EduHist, string UserID) {
            base.Channel.UpdateEducationHistory(EduHist, UserID);
        }
        
        public System.Threading.Tasks.Task UpdateEducationHistoryAsync(WcfAESJobs.Client.UserService.EducationHistory_User[] EduHist, string UserID) {
            return base.Channel.UpdateEducationHistoryAsync(EduHist, UserID);
        }
        
        public void UpdateWorkHistory(WcfAESJobs.Client.UserService.WorkHistory_User[] WorkHist, string UserID) {
            base.Channel.UpdateWorkHistory(WorkHist, UserID);
        }
        
        public System.Threading.Tasks.Task UpdateWorkHistoryAsync(WcfAESJobs.Client.UserService.WorkHistory_User[] WorkHist, string UserID) {
            return base.Channel.UpdateWorkHistoryAsync(WorkHist, UserID);
        }
    }
}
